# A GitHub Action to generate database documentation using SchemaSpy.
# This will build the documentation and create a PR to main if there are changes.
# This will activate on pushes to the main branch.
---
name: Build SchemaSpy Documentation
on:
  workflow_dispatch:
  push:
    branches:
      - main
    
jobs:
  schemaspy-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Start PostgreSQL
        run: docker-compose up -d
      - name: Wait for PostgreSQL to be ready
        run: |
          for i in {1..30}; do
            if pg_isready -h localhost -p 5432 -U postgres; then
              echo "PostgreSQL is ready!"
              break
            fi
            echo "Waiting for PostgreSQL to be ready..."
            sleep 5
          done
      - name: Run SchemaSpy
        run: |
          docker run --rm 
            -it 
            -v "$(pwd)/schemaspy":/output 
            --network host 
            schemaspy/schemaspy:latest 
            -t pgsql 
            -db prt_db 
            -host localhost 
            -u postgres 
            -p postgres 
            -all
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          sign-commits: true
          title: 'Update SchemaSpy Documentation [GH Action]'
          body: 'This PR updates the SchemaSpy documentation.'
          
